### ISSUE TITLE
Zlib library patch not completing along side avro update - TX2

### ISSUE THREAD

**Issue by JonathanJenk** [jetsonhacks/installTensorFlowTX1#12]
Used these scripts on a TX1 and a TX2 today, the TX1 did not find these problems, however with the TX2 the patch didnt seem to apply for the Zlib move. Manually changing the tensorflow/tensorflow/workspace.bzl file to reflect the move worked.

The avro.tar file has also changed location (again, only present on the TX2) which only needed the 1.8.0 version adapted to 1.8.2, eg:  "avro-doc-1.8.2.tar.gz". 

Maybe not always useful, if needing the latest, but using this means the versions synced.

**Comment by jetsonhacks** [comment]
There is a separate repository for the TX2 and TensorFlow: https://github.com/jetsonhacks/installTensorFlowTX2
 Thank you for the information here.
