### ISSUE TITLE
Tensorflow version 

### ISSUE THREAD

**Issue by abhiagwl4262** [jetsonhacks/installTensorFlowTX1#14]
Which is the correct git repository out of "https://github.com/jetsonhacks/installTensorFlowTX1/" and "https://github.com/corenel/installTensorFlowTX1/tree/master/scriptshttps://github.com/corenel/installTensorFlowTX1/" ? I want to install tensorflow 1.0 with python 2.7.

**Comment by jetsonhacks** [comment]
The current version is this repository is for TensorFlow 0.11
You will need to investigate other repositories on your own.
