### ISSUE TITLE
ERROR: crosstool_wrapper_driver_is_not_gcc failed: error executing command 

### ISSUE THREAD

**Issue by AmosLewis** [jetsonhacks/installTensorFlowTX1#19]
When I use sudo ./buildTensorFlow.sh , it comes out with this error. I have try to change bazel version from 0.5.2 to 0.5.3 to 0.5.4 version, this error cannot be fixed.  

INFO: From Compiling tensorflow/contrib/boosted_trees/lib/utils/batch_features.cc:
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/contrib/boosted_trees/lib/utils/optional_value.h:19,
                 from ./tensorflow/contrib/boosted_trees/lib/utils/example.h:21,
                 from ./tensorflow/contrib/boosted_trees/lib/utils/examples_iterable.h:21,
                 from ./tensorflow/contrib/boosted_trees/lib/utils/batch_features.h:19,
                 from tensorflow/contrib/boosted_trees/lib/utils/batch_features.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_LTImpl(const T1&, const T2&, const char*) [with T1 = long long int; T2 = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
./tensorflow/core/util/sparse/dim_comparator.h:56:7:   required from here
./tensorflow/core/platform/default/logging.h:231:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LT, < )
                                   ^
./tensorflow/core/platform/macros.h:76:29: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (x)
                             ^
./tensorflow/core/platform/default/logging.h:231:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LT, < )
 ^
# ERROR: /home/ubuntu/tensorflow/tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_root/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=5.3 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=5 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -D_FORCE_INLINES -D_MWAITXINTRIN_H_INCLUDED '-std=c++11' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DSNAPPY -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/local_linux-py3-opt/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-py3-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-py3-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/local_linux-py3-opt/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/local_linux-py3-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -iquote external/snappy -iquote bazel-out/local_linux-py3-opt/genfiles/external/snappy -iquote external/local_config_cuda -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-py3-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/stream_executor/cuda/cuda_blas.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o).
tensorflow/stream_executor/cuda/cuda_blas.cc: In member function 'virtual bool perftools::gputools::cuda::CUDABlas::GetBlasGemmAlgorithms(std::vector<long long int>*)':
## tensorflow/stream_executor/cuda/cuda_blas.cc:1927:9: error: 'CUBLAS_GEMM_ALGO5' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
         ^
## tensorflow/stream_executor/cuda/cuda_blas.cc:1927:28: error: 'CUBLAS_GEMM_ALGO6' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                            ^
## tensorflow/stream_executor/cuda/cuda_blas.cc:1927:47: error: 'CUBLAS_GEMM_ALGO7' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                                               ^
## tensorflow/stream_executor/cuda/cuda_blas.cc:1927:64: error: unable to deduce 'std::initializer_list<_Tp>&&' from '{CUBLAS_GEMM_DFALT, CUBLAS_GEMM_ALGO0, CUBLAS_GEMM_ALGO1, CUBLAS_GEMM_ALGO2, CUBLAS_GEMM_ALGO3, CUBLAS_GEMM_ALGO4, <expression error>, <expression error>, <expression error>}'
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                                                                ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasOperation_t perftools::gputools::cuda::{anonymous}::CUDABlasTranspose(perftools::gputools::blas::Transpose)':
tensorflow/stream_executor/cuda/cuda_blas.cc:411:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasFillMode_t perftools::gputools::cuda::{anonymous}::CUDABlasUpperLower(perftools::gputools::blas::UpperLower)':
tensorflow/stream_executor/cuda/cuda_blas.cc:422:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasDiagType_t perftools::gputools::cuda::{anonymous}::CUDABlasDiagonal(perftools::gputools::blas::Diagonal)':
tensorflow/stream_executor/cuda/cuda_blas.cc:433:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cudaDataType_t perftools::gputools::cuda::{anonymous}::CUDAComputationType(perftools::gputools::blas::ComputationType)':
tensorflow/stream_executor/cuda/cuda_blas.cc:527:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cublasSideMode_t perftools::gputools::cuda::{anonymous}::CUDABlasSide(perftools::gputools::blas::Side)':
tensorflow/stream_executor/cuda/cuda_blas.cc:444:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 437.153s, Critical Path: 53.12s

**Comment by jetsonhacks** [comment]
What version of L4T are you running?

**Comment by AmosLewis** [comment]
L4T 24.2.1
Board:t210ref
Ubuntu 16.04.3 LTS
Kernel version:3.10.96-tegra

**Comment by jetsonhacks** [comment]
L4T 24.2.1 is Ubuntu 14.04. Did you upgrade to 16.04 somehow?

**Comment by AmosLewis** [comment]
Nope. I use your jetsonUtilities to show the information.

**Comment by AmosLewis** [comment]
The above question is caused by installing tensorflow 1.3. I found my system is cudnn 5.1.5 just now. So I choose another script wrote by you. I have just use your installTensorFlowTX1-vL4T27.1TF0.11 packages. But the new error comes out when I run the installPrerequistes.sh

*** Building codegen requires Protobuf version 3.0.0-beta-3
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp
FAILURE: Build failed with an exception.

* What went wrong:
java.io.FileNotFoundException: /home/ubuntu/grpc-java/.gradle/2.13/taskArtifacts/cache.properties.lock (Permission denied)
> /home/ubuntu/grpc-java/.gradle/2.13/taskArtifacts/cache.properties.lock (Permission denied)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

After a while it output the final error.


INFO: From Javac src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_JarOwner.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
WARNING: Worker strategy cannot execute this Javac action, because the action's execution info does not contain 'supports-workers=1'.
WARNING: Worker strategy cannot execute this Javac action, because the action's execution info does not contain 'supports-workers=1'.
WARNING: Worker strategy cannot execute this Javac action, because the action's execution info does not contain 'supports-workers=1'.
WARNING: Worker strategy cannot execute this Javac action, because the action's execution info does not contain 'supports-workers=1'.
WARNING: Worker strategy cannot execute this Javac action, because the action's execution info does not contain 'supports-workers=1'.
WARNING: Worker strategy cannot execute this Javac action, because the action's execution info does not contain 'supports-workers=1'.
WARNING: Javac worker (id 1) can no longer be used, because its process terminated itself or got killed.
ERROR: /home/ubuntu/bazel/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:20:1: Java compilation in rule '//src/tools/android/java/com/google/devtools/build/android/ziputils:ziputils_lib' failed: Worker process did not return a correct WorkResponse. This is probably caused by a bug in the worker, writing unexpected other data to stdout.
Target //src:bazel failed to build

**Comment by jetsonhacks** [comment]
The version of JAVA used with the version of Tensorflow originally was 151. Since these scripts were written, JAVA has changed to 161, but the PPA still points to 151 which has been archived. I do not understand yet what is required to fix this, but Bazel seems to have more problems than most other libraries of changing versions.

See issue 20: https://github.com/jetsonhacks/installTensorFlowTX1/issues/20
