### ISSUE TITLE
test fail help me..

### ISSUE THREAD

**Issue by vusdo** [jetsonhacks/installTensorFlowTX1#2]
`
nvidia@tegra-ubuntu:~/tensorflow$ time python tensorflow/models/image/mnist/convolutional.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] **_Couldn't open CUDA library libcudnn.so.5.1.5. LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64:_**
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3448] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] ARM has no NUMA node, hardcoding to return zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: NVIDIA Tegra X1
major: 5 minor: 3 memoryClockRate (GHz) 0.072
pciBusID 0000:00:00.0
Total memory: 3.90GiB
Free memory: 1.54GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0)
Initialized!
F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] could not find cudnnCreate in cudnn DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate
Aborted

real	0m6.081s
user	0m4.210s
sys	0m1.680s

`

`
nvidia@tegra-ubuntu:/usr/local/cuda-8.0/lib64$ ls -al | grep libcudnn 

lrwxrwxrwx 1 root root        13 Dec 28 20:12 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root        17 Dec 28 20:12 libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxrwxrwx 1 root root  79337624 Dec 28 20:12 libcudnn.so.5.1.5
-rw-r--r-- 1 root root  69756172 Dec 28 20:12 libcudnn_static.a
`

**Comment by jetsonhacks** [comment]
On this TX1, the libcudnn libraries are in /usr/lib/aarch64-linux-gnu/
Did you use JetPack 2.3.1 to install cuDNN? Has cuDNN been moved?
You may be able to reconfigure it. See the script: setTensorFlow.sh
You can run the configure.sh script in the tensorflow directory manually if need be.

**Comment by vusdo** [comment]
move cudnn default  path : /usr/local/cuda/

cudnn5.1 download and install..
tar xvzf cudnn-8.0-linux-x64-v5.1-ga.tgz
sudo cp -P cuda/include/cudnn.h /usr/local/cuda/include
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*

help me. (__)

**Comment by jetsonhacks** [comment]
You can either move the cudnn libraries as stated above to: /usr/lib/aarch64-linux-gnu/
or reconfigure tensorflow using the configure.sh file.

**Comment by vusdo** [comment]
Success..
tensorflow web site..  never cuDNN Download..
tx1 depend cuDNN install..

Thank you..

**Comment by jetsonhacks** [comment]
Excellent, glad you got it to work.
