### ISSUE TITLE
Error creating swapfile for tensorflow install (TX1)

### ISSUE THREAD

**Issue by engineer1982** [jetsonhacks/installTensorFlowTX1#24]
Hello there.

I am trying to create a swapfile in a usb pendrive 16GB (formated as FAT32). After running the command:

sudo ./createSwapfile.sh -d /media/nvidia/MARCELO -s 8

I get the following errors:

Creating Swapfile at:  /media/nvidia/MARCELO
Swapfile Size:  8G
Automount:  N
fallocate: fallocate failed: Operation not supported
-rwxrwxrwx 1 nvidia nvidia 0 Feb  2 17:01 swapfile
-rwxrwxrwx 1 nvidia nvidia 0 Feb  2 17:01 swapfile
mkswap: error: swap area needs to be at least 40 KiB
swapon: /media/nvidia/MARCELO/swapfile: insecure permissions 0777, 0600 suggested.
swapon: /media/nvidia/MARCELO/swapfile: insecure file owner 1001, 0 (root) suggested.
swapon: /media/nvidia/MARCELO/swapfile: read swap header failed

Any ideas? I am lost (new in linux) and really need to have tensorflow with gpu access in my TX1.

Thanks! :)

**Comment by jetsonhacks** [comment]
Most Linux systems are EXT4. FAT32 has issues with files > 2GB, and most NTSF systems are Macintosh. Unless there you have a very good reason to be compiling this older version from source, you should be using the official NVIDIA TensorFlow .whl files for installation. See:

https://devtalk.nvidia.com/default/topic/1031300/jetson-tx2/tensorflow-1-11-0-wheel-with-jetpack-3-3/post/5246603/#5246603

**Comment by engineer1982** [comment]
Hi! When I googled Tensorflow for TX1 I reached out this GitHub, thought that was the latest for TX1. Is it possible to update the landing page about this new wheel file?

Thanks so much for this information!!! Will download it now. Didn't know I could use the package for TX2 in TX1.

Is there any other newest wheel for opencv as well? 

Have a great Sunday!
