### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by LimSM** [jetsonhacks/installTensorFlowTX1#3]
Hello, Thank you for your instruction.
but i have a build issue.
when i built, i receive the follwing message;
Server finished RPC without an explicit exit code
How to resolve ?

**Comment by jetsonhacks** [comment]
Did you set the local lib using the script:

$ ./setLocalLib

before compiling gprc-java?

What version of L4T are you using?
Is there any more information with the error message?

**Comment by LimSM** [comment]
Hi,
I'm using the version L4T r24.2.1

I tried many times, i got the same message, but the number of compiling isn't same.
following is the recently built message.

[1,215 / 2,435] Compling tensorflow/contrib/tensor_forest/hybrid/core/ops/k_feature_gradient_op.cc

Server finished RPC without an explicit exit code.

Also, I want to know your L4T build options and using swap.
i can't build with swap by shortage of memory.
Thank you.

**Comment by jetsonhacks** [comment]
You probably ran out of memory. As noted in the README.md file, you will need a large swap file to build TensorFlow. If you have no external memory available, a wheel file is available from the link below. However, note that the 4GB memory of the TX1 will limit the complexity of models that can be trained without the use of a swap file. Please see this article for further information:

http://www.jetsonhacks.com/2016/12/30/tensorflow-nvidia-jetson-tx1-development-kit/

**Comment by LimSM** [comment]
Thank you for your assist.
I don't know the existence of the site below.

http://www.jetsonhacks.com/2016/12/21/jetson-tx1-swap-file-and-development-preparation/
