### ISSUE TITLE
Does the scripts support installing tensorflow r1.0?

### ISSUE THREAD

**Issue by JunhongXu** [jetsonhacks/installTensorFlowTX1#6]
Thank you for providing these convenient scripts! Can I use these scripts to install tensorflow r1.0?

More specifically, In the script `cloneTensorflow.sh`, you have `git checkout r0.11`, can I change this to `git checkout r1.0` and run the rest of the scripts to install tensorflow r1.0?

**Comment by jetsonhacks** [comment]
No. There currently is a bug on the Jetson TX1 in the nvcc compiler which causes the build to fail on Tensorflow r1.0.

**Comment by jetsonhacks** [comment]
No. There currently is a bug on the Jetson TX1 in the nvcc compiler which causes the build to fail on Tensorflow r1.0.

**Comment by kwotsin** [comment]
Hi Jetsonhacks, would it be possible to checkout the r0.12 version and still get it up and running?

**Comment by jetsonhacks** [comment]
I do not know, I have not tried it.
